# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1da9489d1453a7c751af6ffa71f2bdb17cb3981931d1911aa61b3f0f6f83b8c8319ba02020162a8738791c8e22348a588d6b3e94009f78893d2213141564ecbd

test:
  secret_key_base: 48795a06a9c62cce0dd09b98447b9c4b4230a86d3899527fe2858b054a03aef95464a39c7ff05925158002c20d5c39cecdf632c1532e5909543d07391d9524e4

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
